services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Maispace\Make\:
    resource: '../Classes/*'

  Maispace\Make\PackageResolver:
    public: true

  Maispace\Make\Command\Component\DataProcessorCommand:
    tags:
      - name: 'console.command'
        command: 'make:dataprocessor'
        description: 'Create a TypoScript data processor'
        schedulable: false

  Maispace\Make\Command\Component\DtoCommand:
    tags:
      - name: 'console.command'
        command: 'make:dto'
        description: 'Create a Data Transfer Object (DTO)'
        schedulable: false

  Maispace\Make\Command\Component\EnumCommand:
    tags:
      - name: 'console.command'
        command: 'make:enum'
        description: 'Create a PHP enum'
        schedulable: false

  Maispace\Make\Command\Component\FactoryCommand:
    tags:
      - name: 'console.command'
        command: 'make:factory'
        description: 'Create a factory class'
        schedulable: false

  Maispace\Make\Command\Component\HookCommand:
    tags:
      - name: 'console.command'
        command: 'make:hook'
        description: 'Create a TYPO3 hook class'
        schedulable: false

  Maispace\Make\Command\Component\InterfaceCommand:
    tags:
      - name: 'console.command'
        command: 'make:interface'
        description: 'Create a PHP interface'
        schedulable: false

  Maispace\Make\Command\Component\ModelCommand:
    tags:
      - name: 'console.command'
        command: 'make:model'
        description: 'Create an Extbase domain model'
        schedulable: false

  Maispace\Make\Command\Component\RepositoryCommand:
    tags:
      - name: 'console.command'
        command: 'make:repository'
        description: 'Create an Extbase domain repository'
        schedulable: false

  Maispace\Make\Command\Component\BackendControllerCommand:
    tags:
      - name: 'console.command'
        command: 'make:backendcontroller'
        description: 'Create a backend controller'
        schedulable: false

  Maispace\Make\Command\Component\CommandCommand:
    tags:
      - name: 'console.command'
        command: 'make:command'
        description: 'Create a console command'
        schedulable: false

  Maispace\Make\Command\Component\ControllerCommand:
    tags:
      - name: 'console.command'
        command: 'make:controller'
        description: 'Create an Extbase action controller'
        schedulable: false

  Maispace\Make\Command\Component\EventCommand:
    tags:
      - name: 'console.command'
        command: 'make:event'
        description: 'Create a PSR-14 event class'
        schedulable: false

  Maispace\Make\Command\Component\EventListenerCommand:
    tags:
      - name: 'console.command'
        command: 'make:eventlistener'
        description: 'Create a PSR-14 event listener'
        schedulable: false

  Maispace\Make\Command\Component\ExceptionCommand:
    tags:
      - name: 'console.command'
        command: 'make:exception'
        description: 'Create a PHP exception class'
        schedulable: false

  Maispace\Make\Command\Component\MigrationCommand:
    tags:
      - name: 'console.command'
        command: 'make:migration'
        description: 'Create a data migration class'
        schedulable: false

  Maispace\Make\Command\Component\MiddlewareCommand:
    tags:
      - name: 'console.command'
        command: 'make:middleware'
        description: 'Create a PSR-15 middleware'
        schedulable: false

  Maispace\Make\Command\Component\RouteEnhancerCommand:
    tags:
      - name: 'console.command'
        command: 'make:routeenhancer'
        description: 'Create a custom route enhancer'
        schedulable: false

  Maispace\Make\Command\Component\ServiceCommand:
    tags:
      - name: 'console.command'
        command: 'make:service'
        description: 'Create a service class'
        schedulable: false

  Maispace\Make\Command\Component\TraitCommand:
    tags:
      - name: 'console.command'
        command: 'make:trait'
        description: 'Create a PHP trait'
        schedulable: false

  Maispace\Make\Command\Component\TypeConverterCommand:
    tags:
      - name: 'console.command'
        command: 'make:typeconverter'
        description: 'Create an Extbase property type converter'
        schedulable: false

  Maispace\Make\Command\Component\UpgradeWizardCommand:
    tags:
      - name: 'console.command'
        command: 'make:upgradewizard'
        description: 'Create a TYPO3 upgrade wizard'
        schedulable: false

  Maispace\Make\Command\Component\UtilityCommand:
    tags:
      - name: 'console.command'
        command: 'make:utility'
        description: 'Create a utility class'
        schedulable: false

  Maispace\Make\Command\Component\ValidatorCommand:
    tags:
      - name: 'console.command'
        command: 'make:validator'
        description: 'Create an Extbase validator'
        schedulable: false

  Maispace\Make\Command\Component\ViewHelperCommand:
    tags:
      - name: 'console.command'
        command: 'make:viewhelper'
        description: 'Create a Fluid ViewHelper'
        schedulable: false
